export const videos = [
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
  {
    id: '12',
    title: 'Hi my name is Mangal. Today we will learn how to connect socage with pitch',
    channel_name: 'Tutorial with Mangal',
    duration: 1236,
    views: 9913,
    added_time: '22 hours ago',
  },
]